### ISSUE TITLE
Named ports not supported

### ISSUE THREAD

**Issue by cbeneke** [kontena/akrobateo#21]
Hi,

I tried to create a LoadBalancer with a named port in it

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-http
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nginx
```

Butn the DS then goes into crashLoop because it does not translate correctly to iptables. Logs:

```
Setting up forwarding from port 80 to 10.106.7.233:http/TCP
iptables v1.6.2: Port `http' not valid

Try `iptables -h' or 'iptables --help' for more information.
```

As kubernetes supports using named targetPorts this should imho be supported by the LB provider :)
