### ISSUE TITLE
ip_forward is not enabled

### ISSUE THREAD

**Issue by dhoard** [kontena/akrobateo#31]
## Synopsis
I am following the article at https://blog.kontena.io/akrobateo-general-purpose-loadbalancer-for-k8s/ to setup Akrobateo on my local Kubernetes cluster (bare metal) installed via RKE.

I have removed the default installed RKE ingress-nginx namespace and controller.

I applied 01_role.yaml, 02_service_account.yaml, 03_role_binding.yaml, and 04_operator.yaml without any issues.

I deployed my sample application.

## Expected Behavior

Akrobateo should expose the application externally.

```
> kubectl get services
```
... should show an external IP address for each of my nodes.

## Actual Behavior

Akrobateo pods failed to start. The logs show `ip_forward is not enabled`.

Looking at `akrobateo/lb-image/entrypoint.sh` this will happen if `cat /proc/sys/net/ipv4/ip_forward` doesn't return `0`.

I have confirmed on all 3 nodes that...

```
>cat /proc/sys/net/ipv4/ip_forward
1
```

```
> kubectl get services
NAME          TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
hello-world   LoadBalancer   10.43.140.99   <pending>     8080:32766/TCP   26m
kubernetes    ClusterIP      10.43.0.1      <none>        443/TCP          122m
```

**Comment by jnummelin** [comment]
Well, MetalLB does not use custom pods with iptables for routing so it works completely differently alltogether. :)

So the LB pods do look like expected with the init containers trying to set `net.ipv4.ip_forward`. Would you be able to run a pure test pod on the system and try out couple of things. So to test out how ip forwarding looks like, run a simple test pod that mimics the LB pod:
```yaml

apiVersion: v1
kind: Pod
metadata:
  name: ip-forward-test
  labels:
    name: ip-forward-test
spec:
  containers:
    - name: test
      command:
        - sh
        - -c
        - sleep 60000
      image: registry.pharos.sh/kontenapharos/akrobateo-lb:latest
      imagePullPolicy: Always
      name: sysctl
      resources: {}
      securityContext:
        privileged: true

```

Then exec yourself into the pod with `kubectl exec -t -i ip-forward-test sh` and run some tests:
```
/ $ sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
/ $ sysctl -w net.ipv4.ip_forward=1
/ $ echo $?
0
/ $ sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
```
